SET FOREIGN_KEY_CHECKS = 0;

DROP PROCEDURE IF EXISTS sp_debe_reintentar;
DROP PROCEDURE IF EXISTS sp_marcar_exito;
DROP PROCEDURE IF EXISTS sp_registrar_error;

DROP TABLE IF EXISTS causas;
DROP TABLE IF EXISTS ebooks;
DROP TABLE IF EXISTS errores_scraping;
DROP TABLE IF EXISTS etapas_juicio;
DROP TABLE IF EXISTS movimientos;
DROP TABLE IF EXISTS pdfs;
DROP TABLE IF EXISTS scraping_log;

